Categories:
  - Navigation
  - Sports & Health
License: GPL-3.0-or-later
SourceCode: https://github.com/Samq64/OfflineGPX
IssueTracker: https://github.com/Samq64/OfflineGPX/issues

AutoName: Offline GPX

RepoType: git
Repo: https://github.com/Samq64/OfflineGPX.git
Binaries: https://github.com/Samq64/OfflineGPX/releases/download/v%v/offline-gpx-%v.apk

Builds:
  - versionName: 0.1.0
    versionCode: 1
    commit: v0.1.0
    subdir: app
    sudo:
      - apt-get update
      - apt-get install -y openjdk-21-jdk-headless
      - update-alternatives --auto java
    gradle:
      - yes

AllowedAPKSigningKeys: fe69a4bae0e3ed1b9272845863c6c5bab9a4621a6017fe2e6159160e8e71cf19

AutoUpdateMode: Version
UpdateCheckMode: Tags
CurrentVersion: 0.1.0
CurrentVersionCode: 1
